import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";

test("admin exposes persisted dashboard range, reset tier, and time format controls", () => {
  const html = readFileSync(new URL("./admin.html", import.meta.url), "utf8");
  const app = readFileSync(new URL("./admin.js", import.meta.url), "utf8");
  const css = readFileSync(new URL("./admin.css", import.meta.url), "utf8");
  assert.match(html, /id="settingsRangePreset"/);
  assert.match(html, /value="last-reset"/);
  assert.match(html, /id="settingsResetProvider"/);
  assert.match(html, /id="settingsResetTier"/);
  assert.match(html, /id="settingsTimeFormat"/);
  assert.match(html, /value="12h"/);
  assert.match(html, /id="settingsModelBillingMultipliers"/);
  assert.match(html, /id="addModelBillingMultiplier"/);
  assert.match(html, /按模型分别设置/);
  assert.match(html, /不会改写数据库/);
  assert.match(html, /class="settings-section settings-defaults"/);
  assert.match(html, /class="settings-section settings-billing"/);
  assert.match(html, /class="settings-section settings-provider-section"/);
  assert.match(html, /class="panel nodes-panel"/);
  assert.match(html, /id="tokenPanel" class="token-panel"/);
  assert.match(app, /dashboardDefaults/);
  assert.match(app, /modelBillingMultipliers/);
  assert.match(app, /if \(!entries\.length\) entries\.push\(\{ model: "", multiplier: 1 \}\)/);
  assert.match(app, /multiplierInput\.className = "settings-model-billing-multiplier-input"/);
  assert.match(app, /multiplierLabel\.append\(multiplierInput\)/);
  assert.match(app, /metricsLabel\.textContent = "默认指标"/);
  assert.match(app, /showTitleInTrigger: false/);
  assert.match(app, /metricsLabel\.append\(picker\)/);
  assert.match(css, /settings-model-billing-multiplier-input[\s\S]*?width: 100%/);
  assert.match(css, /\.settings-section\s*\{/);
  assert.match(css, /\.nodes-table-wrap\s*\{/);
  assert.match(app, /模型计费倍率必须是 0 到 1000/);
  assert.match(app, /quotaTierPeriodSeconds/);
  assert.match(app, /settingsForm\.addEventListener\("submit"/);
  assert.ok(html.indexOf('id="settingsResetProvider"') < html.indexOf('id="settingsModelBillingMultipliers"'));
});
